language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install codecov
# command to install dependencies
install:
  - pip install .
  - pip install redis
before_script:
  - chmod 777 ./tests/do_test.sh
# command to run tests
script: ./tests/do_test.sh
after_success:
  - codecov